#!/bin/bash

# Setup direnv to automatically load .env files
# This script configures direnv globally for all users

echo "🔧 Setting up direnv for automatic .env loading..."

# Create global direnv config directory
mkdir -p /etc/direnv

# Create a global direnvrc that enables .env loading by default
cat > /etc/direnv/direnvrc << 'EOF'
# Global direnv configuration
# Automatically load .env files if they exist

# Enable loading of .env files
if [ -f .env ]; then
  dotenv .env
fi
EOF

# Create .envrc in workspace to auto-load .env
cat > /workspace/.envrc << 'EOF'
# Auto-generated by devcontainer setup
# This file enables automatic loading of .env files

# Load .env file if it exists
if [ -f .env ]; then
  dotenv .env
fi
EOF

# Auto-allow the workspace .envrc
direnv allow /workspace

echo "✅ direnv configured to automatically load .env files"
echo "   Your .env file will be loaded automatically when you enter the workspace"